# Generated by Django 4.2.30 on 2026-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulkInquiry',
            new_name='BulkOrder',
        ),
        migrations.AlterModelOptions(
            name='bulkorder',
            options={'verbose_name_plural': 'Bulk Orders'},
        ),
        migrations.AlterField(
            model_name='bulkorder',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='bulk_order_logos/'),
        ),
    ]
